spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:customer}
    username: ${DB_USER:ucode}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: outdoor_customer
server:
  port: 8081
