version: "3.4"

services:
  redis:
    image: redis:7.0.8-alpine
    volumes: 
      - rdb:/data
    ports: 
      - 6379:6379
    hostname: outdoor_cart

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on: 
      - redis

volumes:
   rdb:
