version: "3.4"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes: 
      - es-data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    hostname: outdoor_product
    environment:
       ELASTIC_PASSWORD: secret
       discovery.type: single-node
       xpack.security.enabled: false
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    depends_on: 
      - es

volumes:
   es-data:
